# Site settings
title: Meren'in Fotoğraf Günlüğü
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1" # the base hostname & protocol for your site
twitter_username: username
github_username: username

permalink: /blog/:year/:month/:title

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
