# Site settings
title: Meren'in Fotoğraf Günlüğü
email: a.murat.eren@gmail.com
description: "What description?"
url: "http://meren.org"
twitter_username: merenbey
github_username: meren

markdown:    kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
